In [1]:
import numpy as np

from src.models.logreg import LogReg

import statsmodels.api as sm
import statsmodels.formula.api as smf

In [2]:
df = sm.datasets.spector.load_pandas().data
# Look at info on data
print(sm.datasets.spector.NOTE)

::

    Number of Observations - 32

    Number of Variables - 4

    Variable name definitions::

        Grade - binary variable indicating whether or not a student's grade
                improved.  1 indicates an improvement.
        TUCE  - Test score on economics test
        PSI   - participation in program
        GPA   - Student's grade point average


In [3]:
df

GPA  TUCE  PSI  GRADE
0   2.66  20.0  0.0    0.0
1   2.89  22.0  0.0    0.0
2   3.28  24.0  0.0    0.0
3   2.92  12.0  0.0    0.0
4   4.00  21.0  0.0    1.0
5   2.86  17.0  0.0    0.0
6   2.76  17.0  0.0    0.0
7   2.87  21.0  0.0    0.0
8   3.03  25.0  0.0    0.0
9   3.92  29.0  0.0    1.0
10  2.63  20.0  0.0    0.0
11  3.32  23.0  0.0    0.0
12  3.57  23.0  0.0    0.0
13  3.26  25.0  0.0    1.0
14  3.53  26.0  0.0    0.0
15  2.74  19.0  0.0    0.0
16  2.75  25.0  0.0    0.0
17  2.83  19.0  0.0    0.0
18  3.12  23.0  1.0    0.0
19  3.16  25.0  1.0    1.0
20  2.06  22.0  1.0    0.0
21  3.62  28.0  1.0    1.0
22  2.89  14.0  1.0    0.0
23  3.51  26.0  1.0    0.0
24  3.54  24.0  1.0    1.0
25  2.83  27.0  1.0    1.0
26  3.39  17.0  1.0    1.0
27  2.67  24.0  1.0    0.0
28  3.65  21.0  1.0    1.0
29  4.00  23.0  1.0    1.0
30  3.10  21.0  1.0    0.0
31  2.39  19.0  1.0    1.0

In [4]:


res_logit = smf.logit("GRADE ~ GPA + TUCE + PSI", data=df).fit()
print(res_logit.summary())

Optimization terminated successfully.
         Current function value: 0.402801
         Iterations 7
                           Logit Regression Results                           
Dep. Variable:                  GRADE   No. Observations:                   32
Model:                          Logit   Df Residuals:                       28
Method:                           MLE   Df Model:                            3
Date:                Sat, 06 Jan 2024   Pseudo R-squ.:                  0.3740
Time:                        00:25:21   Log-Likelihood:                -12.890
converged:                       True   LL-Null:                       -20.592
Covariance Type:            nonrobust   LLR p-value:                  0.001502
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -13.0213      4.931     -2.641      0.008     -22.687      -3.356
GPA            2.8261      1.

In [6]:
m = LogReg(df=df,
           outcome="GRADE",
           independent=["GPA", "TUCE", "PSI"])

m.summary()

Converged in 6 iterations.


In [7]:

m.predict(np.array([2.66, 20, 0]))

array([0.02657799])

In [8]:
m.predict_class(np.array([2.66, 20, 0]))

array([0])

In [9]:
m.fitted_values()

array([0.02657799, 0.05950125, 0.18725993, 0.02590164, 0.56989295,
       0.03485827, 0.02650406, 0.051559  , 0.11112666, 0.69351131,
       0.02447037, 0.18999744, 0.32223955, 0.19321116, 0.36098992,
       0.03018375, 0.05362641, 0.03858834, 0.58987249, 0.66078584,
       0.06137585, 0.90484727, 0.24177245, 0.85209089, 0.83829051,
       0.48113304, 0.63542059, 0.30721866, 0.84170413, 0.94534025,
       0.5291172 , 0.11103084])

In [10]:
m.residuals()

array([-0.16523822, -0.25152662, -0.48000592, -0.16306554, -0.15108757,
       -0.1900454 , -0.16500196, -0.23315626, -0.35358121, -0.50424836,
       -0.15837989, -0.48431807, -0.68952706,  0.51063132, -0.75161196,
       -0.1764176 , -0.23804445, -0.20034261, -1.19927733, -0.39570416,
       -0.25571305, -2.08373478, -0.56468159, -2.40018928, -1.27682431,
        0.03704813, -0.32018433, -0.66592558, -1.30592369, -3.15872565,
       -1.06003334,  0.6465903 ])